config/routes.rb
Rails.application.routes.draw do
  
  root "projects#index"
  devise_for :users
  resources :users, :only => [:show]

  namespace :admin do
    root :to => "base#index"
    resources :assignments   
  end
  
  get "/join", to: "users#join"
  get "/unjoin", to: "users#unjoin"

  get "/my_teams", to: "users#my_teams"
  get "/my_tasks", to: "users#my_tasks"
  get "/my_projects", to: "users#my_projects"

  get "/remove_project", to: "teams#remove_project"
  
  post "/posts/:post_id/comments", to: "comments#add_comment", as: 'post/comments'

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :posts
    resources :teams
  end

  resources :tasks
  resources :posts
  resources :comments

  resources :teams do
    resources :projects
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :task
	belongs_to :post
	validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_project, only: [:create]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    set_task
    @comment = @task.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to [@project, @task], notice: 'Comment was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_comment
    set_post
    @comment = @post.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }   
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_task
      @task = Task.find(params[:task_id])
    end

    def set_post
      @post = Post.find(params[:post_id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content, class: "form-control"%>
  </div>
  <div class="actions">
    <%= f.submit "Create comment", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to "Delete Comment", @comment, method: :delete,
data: { confirm: "Are you sure you want to delete this comment?"} %>
<p></p>