config/routes.rb
Rails.application.routes.draw do
  
  root "projects#index"
  devise_for :users
  resources :users, :only => [:show]

  namespace :admin do
    root :to => "base#index"
    resources :assignments   
  end
  
  get "/join", to: "users#join"
  get "/unjoin", to: "users#unjoin"

  get "/my_teams", to: "users#my_teams"
  get "/my_tasks", to: "users#my_tasks"
  get "/my_projects", to: "users#my_projects"

  get "/remove_project", to: "teams#remove_project"
  
  post "/posts/:post_id/comments", to: "comments#add_comment", as: 'post/comments'

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :posts
    resources :teams
  end

  resources :tasks
  resources :posts
  resources :comments

  resources :teams do
    resources :projects
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks, dependent: :destroy
	has_many :posts, dependent: :destroy
	has_many :assignments, dependent: :destroy
	has_many :teams, through: :assignments
	validates :name, presence: true
    validates :summary, presence: true, length: { minimum: 10 }
    validates :start_date, presence: true
    validates :end_date, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end
  
  def show
    @post = Post.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render "new"
    end
  end

  def update
    if @project.update(project_params)
      
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render "edit"
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project has been destroyed."
    redirect_to projects_path
  end

  private
    def project_params
  	  params.require(:project).permit(:name, :summary, :start_date, :end_date)
    end

    def set_project
      @project = Project.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = "The project you were looking for could not be found."
        redirect_to projects_path
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<% if @project.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@project.errors.count, "error") %> 
       prohibited this project from being saved:</h2>

     <ul>
     <% @project.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
  <% end %>
<p>
<%= f.label :name %><br />
<%= f.text_field :name %>
</p>
<p>
<%= f.label :summary %><br />
<%= f.text_area :summary %>
</p>
<p>
<%= f.label :start_date %><br />
<%= f.date_field :start_date%>
</p>
<p>
<%= f.label :end_date %><br />
<%= f.date_field :end_date %>
<%= f.submit "Project", class: "btn btn-primary btn-small" %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit project</h1>
<%= render "form" %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<table id="projects" >
  <thead>
	  <tr>
	    <th>Name</th>
	    <th>Summary</th>
	    <th>Start_date</th>
	    <th>End_date</th>
	  </tr>
  </thead>

  <tbody>
	  <% @projects.each do |project| %>
	  <tr>
	    <td><%= link_to project.name, project %></td>
	    <td><%= project.summary %></td>
	    <td><%= project.start_date %></td>
	    <td><%= project.end_date %></td>
	  </tr>
	  <% end %>
  <tbody>
</table>

<% if can? :manage, Project %>
  <%= link_to "New Project", new_project_path, class: "btn btn-success" %>
<% end %>

app/views/projects/new.html.erb
<h3>New Project</h3>
<%= render "form" %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<span class="content">
  <%= @project.summary %>
</span>
<p></p>

<ul id='teams'>
  This project belongs to following teams:
  <% @project.teams.each do |team| %>
     <li>
      <%= link_to team.name, [@project, team] %>
    </li>
  <% end %>
</ul>

<h3>Our tasks</h3>
<table id="tasks">
  <thead>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Status</th>
    <th>Start_date</th>
    <th>Due_date</th>
    <th>Estimation</th>
  </tr>
  </thead>
  
  <tbody>
  <% @project.tasks.each do |task| %>
  <tr>
    <td><%= link_to task.title, [@project, task] %></td>
    <td><%= task.content %></td>
    <td><%= task.status %></td>
    <td><%= task.start_date %></td>
    <td><%= task.due_date %></td>
    <td><%= task.estimation %></td>
  </tr>
  <% end %>
  </tbody>
</table>

<% if can? :manage, Project %>
  <%= link_to "Edit Project", edit_project_path(@project), class: "btn btn-primary" %>
  <%= link_to "Delete Project",
  	project_path(@project),
  	method: :delete,
  	data: { confirm:
  	"Are you sure you want to delete this project?" },
    class: "btn btn-danger" %> 
<% end %>
<%= link_to "Add Task", new_project_task_path(@project), class: "btn btn-success" %>
<p></p>

<%= form_for [@project, @post] do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :New_post %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Create post", class: "btn btn-primary"%>
  </div>
<% end %>

<h2>Posts</h2>

<% @project.posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.content, post %></h2>
    <p class="date_and_author"><%= "#{post.created_at.strftime("%B %d, %Y")} by #{post.user.first_name}"%></p>
  </div>
<% end %>