config/routes.rb
Rails.application.routes.draw do
  
  root "projects#index"
  devise_for :users
  resources :users, :only => [:show]

  namespace :admin do
    root :to => "base#index"
    resources :assignments   
  end
  
  get "/join", to: "users#join"
  get "/unjoin", to: "users#unjoin"

  get "/my_teams", to: "users#my_teams"
  get "/my_tasks", to: "users#my_tasks"
  get "/my_projects", to: "users#my_projects"

  get "/remove_project", to: "teams#remove_project"
  
  post "/posts/:post_id/comments", to: "comments#add_comment", as: 'post/comments'

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :posts
    resources :teams
  end

  resources :tasks
  resources :posts
  resources :comments

  resources :teams do
    resources :projects
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Tasks
    by <a href="http://github.com/vazov">Alexey Galenko</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", root_path %></li>
      <li><%= link_to "Contact", root_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Tasks", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right"> 
        <% if user_signed_in? %>
          <li><%= link_to "My Tasks", my_tasks_path %></li>
          <li><%= link_to "My Projects", my_projects_path %></li>
          <li><%= link_to "My Teams", my_teams_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.first_name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "All_teams", teams_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>
              <% admins_only do %>
              <li>
                <%= link_to "Admin", admin_root_path %>
              </li>  
              <% end %>
            </ul>
          </li>
        <% else %>
          <li><%= link_to('SignUp', new_user_registration_path) %></li>
          <li><%= link_to('Login', new_user_session_path) %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class='flash' id='<%= key %>'>
        <%= value %>
      </div>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </div>
</body>
</html>